spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{}:{}/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: { }
    password: { }



  jpa:
    hibernate:
      ddl-auto: validate # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
    context-path: /
  port: 3000

mail:
  address:
    admin: admin@gmail.com